<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1lwwf0g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1lwwf0g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1lwwf0g.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1lwwf0g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1lwwf0g\appDevDebugProjectContainer(array(
    'container.build_hash' => '1lwwf0g',
    'container.build_id' => '39b9e26a',
    'container.build_time' => 1524849542,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1lwwf0g');
