<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\LoginController:login' => function () {
    return ${($_ = isset($this->services['service_locator.9wcmsvk']) ? $this->services['service_locator.9wcmsvk'] : $this->load('getServiceLocator_9wcmsvkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\LoginController:loginRedirect' => function () {
    return ${($_ = isset($this->services['service_locator.9wcmsvk']) ? $this->services['service_locator.9wcmsvk'] : $this->load('getServiceLocator_9wcmsvkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\LoginController:logout' => function () {
    return ${($_ = isset($this->services['service_locator.9wcmsvk']) ? $this->services['service_locator.9wcmsvk'] : $this->load('getServiceLocator_9wcmsvkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\LoginController::login' => function () {
    return ${($_ = isset($this->services['service_locator.9wcmsvk']) ? $this->services['service_locator.9wcmsvk'] : $this->load('getServiceLocator_9wcmsvkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\LoginController::loginRedirect' => function () {
    return ${($_ = isset($this->services['service_locator.9wcmsvk']) ? $this->services['service_locator.9wcmsvk'] : $this->load('getServiceLocator_9wcmsvkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\LoginController::logout' => function () {
    return ${($_ = isset($this->services['service_locator.9wcmsvk']) ? $this->services['service_locator.9wcmsvk'] : $this->load('getServiceLocator_9wcmsvkService.php')) && false ?: '_'};
})));
