<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1nuxftj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1nuxftj/appProdProjectContainer.php') {
    touch(__DIR__.'/Container1nuxftj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container1nuxftj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container1nuxftj\appProdProjectContainer(array(
    'container.build_hash' => '1nuxftj',
    'container.build_id' => '119ee29d',
    'container.build_time' => 1524838226,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1nuxftj');
